#!/bin/bash
# Script para obtener logs de GitHub Actions

echo "================================================"
echo "  Obtener Logs de GitHub Actions"
echo "================================================"
echo ""

REPO="vejeta/stremio-distroless"
BRANCH="claude/stremio-distroless-context-011CV1LQ3sR4RtSh93JorpEe"

echo "📋 Opción 1: Ver en GitHub Web"
echo "==============================="
echo ""
echo "1. Ve a: https://github.com/$REPO/actions"
echo "2. Filtra por branch: $BRANCH"
echo "3. Click en el workflow que falló (ícono rojo ❌)"
echo "4. Click en el job que falló"
echo "5. Expande el step que tiene error"
echo "6. Copia las últimas 30-50 líneas del error"
echo ""

echo "📋 Opción 2: Usar GitHub CLI (gh)"
echo "===================================="
echo ""
echo "# Ver últimos workflows"
echo "gh run list --repo $REPO --branch $BRANCH --limit 5"
echo ""
echo "# Ver detalles de un run específico (usar el ID del comando anterior)"
echo "gh run view <RUN_ID> --repo $REPO"
echo ""
echo "# Ver logs del run que falló"
echo "gh run view <RUN_ID> --repo $REPO --log-failed"
echo ""
echo "# Ver todos los logs"
echo "gh run view <RUN_ID> --repo $REPO --log"
echo ""

echo "📋 Opción 3: API de GitHub"
echo "============================"
echo ""
echo "# Obtener últimos workflow runs"
echo "curl -H 'Accept: application/vnd.github.v3+json' \\"
echo "  'https://api.github.com/repos/$REPO/actions/runs?branch=$BRANCH&per_page=5'"
echo ""

echo "================================================"
echo "  Información a Compartir"
echo "================================================"
echo ""
echo "Para que pueda ayudarte mejor, necesito:"
echo ""
echo "1. ✅ Nombre del workflow que falló"
echo "   Ejemplo: 'Build and Security Scan - Multi-Ecosystem'"
echo ""
echo "2. ✅ Nombre del job que falló"
echo "   Ejemplo: 'build-and-scan (wolfi, gui)'"
echo ""
echo "3. ✅ Nombre del step que falló"
echo "   Ejemplo: 'Build Docker image' o 'Test container security posture'"
echo ""
echo "4. ✅ Las últimas 30-50 líneas del error"
echo "   (Copia todo el texto del error, incluyendo el comando que se ejecutó)"
echo ""
echo "5. ✅ El commit SHA donde falló"
echo "   Ejemplo: 2f6417d o d7f501a"
echo ""

echo "================================================"
echo "  Comandos Rápidos"
echo "================================================"
echo ""

# Verificar si gh está instalado
if command -v gh > /dev/null 2>&1; then
    echo "✅ GitHub CLI (gh) está instalado"
    echo ""
    echo "Ejecutando: gh run list --repo $REPO --branch $BRANCH --limit 5"
    echo "----------------------------------------"
    gh run list --repo $REPO --branch $BRANCH --limit 5 2>&1 || echo "⚠️  No se pudo obtener la lista (requiere autenticación)"
    echo ""
else
    echo "❌ GitHub CLI (gh) no está instalado"
    echo "   Instalar: https://cli.github.com/"
    echo ""
fi

echo "================================================"
echo ""
echo "💡 Tip: Una vez tengas los logs, compártelos aquí y podré:"
echo "   - Identificar el problema específico"
echo "   - Proponer una solución"
echo "   - Actualizar el workflow si es necesario"
echo ""
